<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Test Report</title>
    <link href="assets/style.css" rel="stylesheet" type="text/css"/></head>
  <body onLoad="init()">
    <script>/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */


function toArray(iter) {
    if (iter === null) {
        return null;
    }
    return Array.prototype.slice.call(iter);
}

function find(selector, elem) { // eslint-disable-line no-redeclare
    if (!elem) {
        elem = document;
    }
    return elem.querySelector(selector);
}

function findAll(selector, elem) {
    if (!elem) {
        elem = document;
    }
    return toArray(elem.querySelectorAll(selector));
}

function sortColumn(elem) {
    toggleSortStates(elem);
    const colIndex = toArray(elem.parentNode.childNodes).indexOf(elem);
    let key;
    if (elem.classList.contains('result')) {
        key = keyResult;
    } else if (elem.classList.contains('links')) {
        key = keyLink;
    } else {
        key = keyAlpha;
    }
    sortTable(elem, key(colIndex));
}

function showAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(showExtras);
}

function hideAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(hideExtras);
}

function showExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.remove('collapsed');
    expandcollapse.classList.remove('expander');
    expandcollapse.classList.add('collapser');
}

function hideExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.add('collapsed');
    expandcollapse.classList.remove('collapser');
    expandcollapse.classList.add('expander');
}

function showFilters() {
    const filterItems = document.getElementsByClassName('filter');
    for (let i = 0; i < filterItems.length; i++)
        filterItems[i].hidden = false;
}

function addCollapse() {
    // Add links for show/hide all
    const resulttable = find('table#results-table');
    const showhideall = document.createElement('p');
    showhideall.innerHTML = '<a href="javascript:showAllExtras()">Show all details</a> / ' +
                            '<a href="javascript:hideAllExtras()">Hide all details</a>';
    resulttable.parentElement.insertBefore(showhideall, resulttable);

    // Add show/hide link to each result
    findAll('.col-result').forEach(function(elem) {
        const collapsed = getQueryParameter('collapsed') || 'Passed';
        const extras = elem.parentNode.nextElementSibling;
        const expandcollapse = document.createElement('span');
        if (extras.classList.contains('collapsed')) {
            expandcollapse.classList.add('expander');
        } else if (collapsed.includes(elem.innerHTML)) {
            extras.classList.add('collapsed');
            expandcollapse.classList.add('expander');
        } else {
            expandcollapse.classList.add('collapser');
        }
        elem.appendChild(expandcollapse);

        elem.addEventListener('click', function(event) {
            if (event.currentTarget.parentNode.nextElementSibling.classList.contains('collapsed')) {
                showExtras(event.currentTarget);
            } else {
                hideExtras(event.currentTarget);
            }
        });
    });
}

function getQueryParameter(name) {
    const match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
    return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
}

function init () { // eslint-disable-line no-unused-vars
    resetSortHeaders();

    addCollapse();

    showFilters();

    sortColumn(find('.initial-sort'));

    findAll('.sortable').forEach(function(elem) {
        elem.addEventListener('click',
            function() {
                sortColumn(elem);
            }, false);
    });
}

function sortTable(clicked, keyFunc) {
    const rows = findAll('.results-table-row');
    const reversed = !clicked.classList.contains('asc');
    const sortedRows = sort(rows, keyFunc, reversed);
    /* Whole table is removed here because browsers acts much slower
     * when appending existing elements.
     */
    const thead = document.getElementById('results-table-head');
    document.getElementById('results-table').remove();
    const parent = document.createElement('table');
    parent.id = 'results-table';
    parent.appendChild(thead);
    sortedRows.forEach(function(elem) {
        parent.appendChild(elem);
    });
    document.getElementsByTagName('BODY')[0].appendChild(parent);
}

function sort(items, keyFunc, reversed) {
    const sortArray = items.map(function(item, i) {
        return [keyFunc(item), i];
    });

    sortArray.sort(function(a, b) {
        const keyA = a[0];
        const keyB = b[0];

        if (keyA == keyB) return 0;

        if (reversed) {
            return keyA < keyB ? 1 : -1;
        } else {
            return keyA > keyB ? 1 : -1;
        }
    });

    return sortArray.map(function(item) {
        const index = item[1];
        return items[index];
    });
}

function keyAlpha(colIndex) {
    return function(elem) {
        return elem.childNodes[1].childNodes[colIndex].firstChild.data.toLowerCase();
    };
}

function keyLink(colIndex) {
    return function(elem) {
        const dataCell = elem.childNodes[1].childNodes[colIndex].firstChild;
        return dataCell == null ? '' : dataCell.innerText.toLowerCase();
    };
}

function keyResult(colIndex) {
    return function(elem) {
        const strings = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed',
            'Skipped', 'Passed'];
        return strings.indexOf(elem.childNodes[1].childNodes[colIndex].firstChild.data);
    };
}

function resetSortHeaders() {
    findAll('.sort-icon').forEach(function(elem) {
        elem.parentNode.removeChild(elem);
    });
    findAll('.sortable').forEach(function(elem) {
        const icon = document.createElement('div');
        icon.className = 'sort-icon';
        icon.textContent = 'vvv';
        elem.insertBefore(icon, elem.firstChild);
        elem.classList.remove('desc', 'active');
        elem.classList.add('asc', 'inactive');
    });
}

function toggleSortStates(elem) {
    //if active, toggle between asc and desc
    if (elem.classList.contains('active')) {
        elem.classList.toggle('asc');
        elem.classList.toggle('desc');
    }

    //if inactive, reset all other functions and add ascending active
    if (elem.classList.contains('inactive')) {
        resetSortHeaders();
        elem.classList.remove('inactive');
        elem.classList.add('active');
    }
}

function isAllRowsHidden(value) {
    return value.hidden == false;
}

function filterTable(elem) { // eslint-disable-line no-unused-vars
    const outcomeAtt = 'data-test-result';
    const outcome = elem.getAttribute(outcomeAtt);
    const classOutcome = outcome + ' results-table-row';
    const outcomeRows = document.getElementsByClassName(classOutcome);

    for(let i = 0; i < outcomeRows.length; i++){
        outcomeRows[i].hidden = !elem.checked;
    }

    const rows = findAll('.results-table-row').filter(isAllRowsHidden);
    const allRowsHidden = rows.length == 0 ? true : false;
    const notFoundMessage = document.getElementById('not-found-message');
    notFoundMessage.hidden = !allRowsHidden;
}
</script>
    <h1>reports.html</h1>
    <p>Report generated on 12-Jun-2021 at 18:53:50 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a> v3.1.1</p>
    <h2>Environment</h2>
    <table id="environment">
      <tr>
        <td>Packages</td>
        <td>{"pluggy": "0.13.1", "py": "1.10.0", "pytest": "6.2.4"}</td></tr>
      <tr>
        <td>Platform</td>
        <td>Windows-10-10.0.19041-SP0</td></tr>
      <tr>
        <td>Plugins</td>
        <td>{"html": "3.1.1", "metadata": "1.11.0"}</td></tr>
      <tr>
        <td>Python</td>
        <td>3.9.4</td></tr></table>
    <h2>Summary</h2>
    <p>3 tests ran in 180.44 seconds. </p>
    <p class="filter" hidden="true">(Un)check the boxes to filter the results.</p><input checked="true" class="filter" data-test-result="passed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="passed">3 passed</span>, <input checked="true" class="filter" data-test-result="skipped" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="skipped">0 skipped</span>, <input checked="true" class="filter" data-test-result="failed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="failed">0 failed</span>, <input checked="true" class="filter" data-test-result="error" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="error">0 errors</span>, <input checked="true" class="filter" data-test-result="xfailed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xfailed">0 expected failures</span>, <input checked="true" class="filter" data-test-result="xpassed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xpassed">0 unexpected passes</span>
    <h2>Results</h2>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable result initial-sort" col="result">Result</th>
          <th class="sortable" col="name">Test</th>
          <th class="sortable" col="duration">Duration</th>
          <th class="sortable links" col="links">Links</th></tr>
        <tr hidden="true" id="not-found-message">
          <th colspan="4">No results found. Try to check the filters</th></tr></thead>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">myFramework/test_checkBox.py::TestCheckBox::test_chkbox</td>
          <td class="col-duration">69.09</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>Huurreee pravin
You have selected :
home
desktop
notes
commands
documents
workspace
react
angular
veu
office
public
private
classified
general
downloads
wordFile
excelFile
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">myFramework/test_textBoxQA.py::Testmyframework1::test_homePageAction[getdataz0]</td>
          <td class="col-duration">66.35</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 25, in test_homePageAction
    log.info(&quot;this is to inform you, we are in textbox execution&quot;)
Message: &#x27;this is to inform you, we are in textbox execution&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 26, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;name&#x27;]&quot;).text)
Message: &#x27;Name:navin&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 27, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;email&#x27;]&quot;).text)
Message: &#x27;Email:navin@choo.com&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 28, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;currentAddress&#x27;]&quot;).text)
Message: &#x27;Current Address :go what-ever then right then again left ok&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 29, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;permanentAddress&#x27;]&quot;).text)
Message: &#x27;Permananet Address :left then right then again left ok&#x27;
Arguments: ()
<br/> -------------------------------Captured log call-------------------------------- <br/>INFO     test_homePageAction:test_textBoxQA.py:25 this is to inform you, we are in textbox execution
INFO     test_homePageAction:test_textBoxQA.py:26 Name:navin
INFO     test_homePageAction:test_textBoxQA.py:27 Email:navin@choo.com
INFO     test_homePageAction:test_textBoxQA.py:28 Current Address :go what-ever then right then again left ok
INFO     test_homePageAction:test_textBoxQA.py:29 Permananet Address :left then right then again left ok<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">myFramework/test_textBoxQA.py::Testmyframework1::test_homePageAction[getdataz1]</td>
          <td class="col-duration">32.29</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 25, in test_homePageAction
    log.info(&quot;this is to inform you, we are in textbox execution&quot;)
Message: &#x27;this is to inform you, we are in textbox execution&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 25, in test_homePageAction
    log.info(&quot;this is to inform you, we are in textbox execution&quot;)
Message: &#x27;this is to inform you, we are in textbox execution&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 26, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;name&#x27;]&quot;).text)
Message: &#x27;Name:pravin&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 26, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;name&#x27;]&quot;).text)
Message: &#x27;Name:pravin&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 27, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;email&#x27;]&quot;).text)
Message: &#x27;Email:emailzx@choo.com&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 27, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;email&#x27;]&quot;).text)
Message: &#x27;Email:emailzx@choo.com&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 28, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;currentAddress&#x27;]&quot;).text)
Message: &#x27;Current Address :left then right then again left ok&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 28, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;currentAddress&#x27;]&quot;).text)
Message: &#x27;Current Address :left then right then again left ok&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 29, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;permanentAddress&#x27;]&quot;).text)
Message: &#x27;Permananet Address :left then right then again left ok&#x27;
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 1083, in emit
    msg = self.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 927, in format
    return fmt.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 666, in format
    s = self.formatMessage(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 635, in formatMessage
    return self._style.format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 434, in format
    return self._format(record)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\logging\__init__.py&quot;, line 430, in _format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\runpy.py&quot;, line 87, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\pravi\AppData\Local\Programs\Python\Python39\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(console_main())
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 185, in console_main
    code = main()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\config\__init__.py&quot;, line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\main.py&quot;, line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 126, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 254, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 311, in from_call
    result: Optional[TResult] = func()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 255, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\runner.py&quot;, line 162, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\pravi\appdata\local\programs\python\python39\lib\site-packages\_pytest\python.py&quot;, line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\pravi\PycharmProjects1\MyFramework1\myFramework\test_textBoxQA.py&quot;, line 29, in test_homePageAction
    log.info(self.driver.find_element(By.XPATH, &quot;//div/div/p[@id =&#x27;permanentAddress&#x27;]&quot;).text)
Message: &#x27;Permananet Address :left then right then again left ok&#x27;
Arguments: ()
<br/> -------------------------------Captured log call-------------------------------- <br/>INFO     test_homePageAction:test_textBoxQA.py:25 this is to inform you, we are in textbox execution
INFO     test_homePageAction:test_textBoxQA.py:26 Name:pravin
INFO     test_homePageAction:test_textBoxQA.py:27 Email:emailzx@choo.com
INFO     test_homePageAction:test_textBoxQA.py:28 Current Address :left then right then again left ok
INFO     test_homePageAction:test_textBoxQA.py:29 Permananet Address :left then right then again left ok<br/></div></td></tr></tbody></table></body></html>